#!/bin/sh -e

# -D_DEFAULT_SOURCE: Enable glibc dirent.h dir_type
# Used for ensuring you don't e.g. execute a directory, when reading PATH.
# Avoiding it is annoying and requires other syscalls

case "$1" in
	debug)
		CFLAGS="-g -O0 -D_DEFAULT_SOURCE -Wall -Wextra -Werror -std=c99 -pedantic -fsanitize=address"
		sed -i "s/^#define DEBUG 0$/#define DEBUG 1/" src/util.h
		;;

	*)
		CFLAGS="-O2 -D_DEFAULT_SOURCE -Wall -Wextra -Werror -std=c99 -pedantic"
		sed -i "s/^#define DEBUG 1$/#define DEBUG 0/" src/util.h
		;;
esac

export CFLAGS

make -C src clean
make -C src
sudo cp src/hsh /usr/local/bin/
